PRAGMA foreign_keys = ON;

UPDATE shop_settings
SET store_name = '株式会社雪花 公式ストア',
    corporate_name = CASE WHEN corporate_name = '' OR corporate_name = 'AIBOUX' THEN '株式会社雪花' ELSE corporate_name END,
    updated_at = unixepoch() * 1000
WHERE tenant_id = 'tenant_001'
  AND deleted_at IS NULL;

INSERT OR IGNORE INTO core_products (
  id,
  tenant_id,
  jan_code,
  product_name,
  specification,
  standard_price,
  status,
  inventory_managed,
  shop_sync_enabled,
  mall_publish_enabled,
  description,
  stock_quantity,
  sales_amount,
  gross_margin_rate,
  tags_json,
  memo,
  created_at,
  updated_at
)
VALUES
  (
    'coreprod_tenant_001_4901234567895',
    'tenant_001',
    '4901234567895',
    '軽量ステンレスボトル',
    '500ml / 保温保冷対応',
    2980,
    'active',
    1,
    1,
    1,
    '毎日の通勤や外出に使いやすい、軽量で扱いやすいステンレスボトルです。',
    24,
    0,
    0.42,
    '["雪花","ボトル","日用品"]',
    'AIBOUX Mall MVP initial published item.',
    unixepoch() * 1000,
    unixepoch() * 1000
  ),
  (
    'coreprod_tenant_001_4901234567818',
    'tenant_001',
    '4901234567818',
    '雪花セレクト ギフトタオル',
    'フェイスタオル2枚セット',
    2480,
    'active',
    1,
    1,
    1,
    '贈り物にも日常使いにも向く、やわらかな肌触りのタオルセットです。',
    18,
    0,
    0.38,
    '["雪花","ギフト","タオル"]',
    'AIBOUX Mall MVP initial published item.',
    unixepoch() * 1000,
    unixepoch() * 1000
  );

INSERT INTO shop_products (
  id,
  tenant_id,
  core_product_id,
  shop_name,
  display_name,
  description,
  publish_state,
  seo_title,
  seo_description,
  sale_price,
  cost_price,
  shipping_cost,
  platform_fee_rate,
  stripe_fee_rate,
  ai_keywords_json,
  google_category_id,
  image_r2_keys,
  ai_alt_texts_json,
  mall_enabled,
  approval_required,
  created_by,
  updated_by,
  created_at,
  updated_at
)
VALUES
  (
    'shopprod_tenant_001_4901234567895',
    'tenant_001',
    'coreprod_tenant_001_4901234567895',
    'AIBOUX STORE',
    '軽量ステンレスボトル',
    '毎日の通勤や外出に使いやすい、軽量で扱いやすいステンレスボトルです。保温保冷に対応し、バッグに入れても持ち運びやすいサイズ感です。',
    'published',
    '軽量ステンレスボトル 500ml',
    '保温保冷対応の軽量ステンレスボトル。AIBOUX Mallで購入できます。',
    2980,
    1200,
    500,
    0,
    3.6,
    '["ステンレスボトル","保温","保冷","軽量"]',
    'Home & Garden > Kitchen & Dining > Drinkware',
    '[]',
    '[]',
    1,
    0,
    'phase19_seed',
    'phase19_seed',
    unixepoch() * 1000,
    unixepoch() * 1000
  ),
  (
    'shopprod_tenant_001_4901234567818',
    'tenant_001',
    'coreprod_tenant_001_4901234567818',
    'AIBOUX STORE',
    '雪花セレクト ギフトタオル',
    '贈り物にも日常使いにも向く、やわらかな肌触りのタオルセットです。清潔感のある色味で、引っ越し祝いや季節の贈答にも使いやすい商品です。',
    'published',
    '雪花セレクト ギフトタオル 2枚セット',
    'ギフトにも日常使いにも適したフェイスタオル2枚セット。AIBOUX Mallで購入できます。',
    2480,
    980,
    430,
    0,
    3.6,
    '["ギフトタオル","フェイスタオル","贈り物"]',
    'Home & Garden > Linens & Bedding > Towels',
    '[]',
    '[]',
    1,
    0,
    'phase19_seed',
    'phase19_seed',
    unixepoch() * 1000,
    unixepoch() * 1000
  )
ON CONFLICT(tenant_id, core_product_id, shop_name) DO UPDATE SET
  publish_state = 'published',
  mall_enabled = 1,
  approval_required = 0,
  updated_by = 'phase19_seed',
  updated_at = unixepoch() * 1000,
  deleted_at = NULL;
